server:
  port: 9090

spring:
  application:
    name: jooq
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  datasource:
    driver-class-name: org.h2.Driver
    # url: jdbc:h2:mem:test # In-Memory mode
    # url: jdbc:h2:~/test   # embedded Mode
    url: 'jdbc:h2:file:./build/data/test;AUTO_SERVER=TRUE;'
    username: sa
    password: test
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
      encoding: utf-8
      schema-locations: classpath:h2/schema.sql
      data-locations: classpath:h2/data.sql

logging:
  level:
    org:
      springframework:
        jdbc: debug